name: Crowdin Sync

on:
  push:
    branches:
      - main
      - crowdin

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Crowdin CLI
        run: curl -LO https://downloads.crowdin.com/cli/v3/crowdin-cli-linux.zip && unzip crowdin-cli-linux.zip -d /usr/local/bin
      
      - name: Sync with Crowdin
        run: crowdin --config crowdin.yml upload sources
        env:
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
